### ISSUE TITLE
only first external input of container visible when container has more than one external input

### ISSUE THREAD

**Issue by inscripttech** [kometbomb/prototracker-modular#36]
when adding more than one external input inside a container and then exiting to parent synth, container only displays one input

(win-x64 v0.0.4)

**Comment by kometbomb** [comment]
This actually works so that you need to use the mouse wheel to increase the input number for the modules and when you have e.g. EXT0, EXT1 EXT2 in the synth, it will display three inputs. Otherwise it would be impossible to know the order of the EXT inputs (which input slot corresponds to which input module). Not sure if I ever fixed the number not being displayed on the module, though.

**Comment by inscripttech** [comment]
Interesting. _When hovering over a contained external input, scrolling up with the mouse wheel increases the number of inputs of the container._ It does become a little awkward without any visual feedback on the external inputs (i.e. can't see which external input is EXTIN2 when inside the container). Good to know it's possible.

**Comment by kometbomb** [comment]
Yeah it has to do with the text not fitting there. I should fix that asap,
it is a matter of having a shorter text there.

ke 27. toukok. 2020 klo 13.26 inscripttech (notifications@github.com)
kirjoitti:
